---

- hosts: all
  become: true
  tasks:

  - name: install updates (Centos)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["Rocky", "Centos"]

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 & php support
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install httpd & php package
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["Rocky", "Centos"]