---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install updates (Centos)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["Rocky", "Centos"]

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 & php support (Ubuntu)
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install httpd & php package (Centos)
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["Rocky", "Centos"]

- hosts: db_servers
  become: true
  tasks: 

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install mariadb package (Centos)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ["Rocky", "Centos"]

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest