---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ['Debian','Ubuntu']

  - name: install updates (Centos)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ['Rocky','Centos']

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 & php support (Ubuntu)
    tags: apaches,apache2,Ubuntu,Debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ['Debian','Ubuntu']

  - name: install httpd & php package (Centos)
    tags: apache,httpd,Rocky,Centos
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ['Rocky','Centos']

  - name: start httpd (Centos)
    tags: apache,httpd,Rocky,Centos
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution in ['Rocky','Centos']

  - name: copy default html file to site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks: 

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu,debian
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ['Debian','Ubuntu']

  - name: install mariadb package (Centos)
    tags: db,mariadb,rocky,centos
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ['Rocky','Centos']

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest